name: shopping_cart_api
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  json_annotation: ^4.0.1
  sqflite: ^2.0.0+3

dev_dependencies:
  build_runner: ^2.1.0
  json_serializable: ^4.1.3
  test: ^1.17.0
  very_good_analysis: ^2.3.0
