name: shopping_cart
description: A shopping cart flutter_bloc example.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  bloc: ^7.0.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  flutter_hooks: ^0.18.0
  freezed_annotation: ^0.14.2
  hydrated_bloc: ^7.0.1
  search_filter_repository:
    path: packages/search_filter_repository
  shopping_cart_repository:
    path: packages/shopping_cart_repository

dev_dependencies:
  bloc_test: ^8.1.0
  build_runner: ^2.1.0
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  mocktail: ^0.1.4
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
