name: examples

on:
  push:
  pull_request:

jobs:
  examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.0
      - name: "Install Tools"
        run: |
          flutter pub global activate melos
      - name: Initialize melos
        run: melos bs
      - name: Run test
        run: melos run test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  build:
    needs: [examples]
    runs-on: ubuntu-latest
    steps:
      - name: noop
        run: echo 'noop'